name: Docker Build SIPp

on:
  workflow_dispatch:
  workflow_call:

jobs:

  load-env-vars:
    runs-on: ubuntu-latest
    outputs:
      DEBIAN_VERSION: ${{ env.DEBIAN_VERSION }}
      SIPP_VERSION: ${{ env.SIPP_VERSION }}
      BUILD_FLAGS: ${{ env.BUILD_FLAGS }}
      SIPP_SCENARIOS_LOCATION: ${{ env.SIPP_SCENARIOS_LOCATION }}
    steps:
      - uses: actions/checkout@v6

      - name: Load environment variables from .env
        run: grep -v '^#' .env | grep -v '^$' >> $GITHUB_ENV

  sipp-build-image-local:
    needs: load-env-vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: sipp
          push: false
          load: true
          tags: sipp:latest
          platforms: linux/amd64
          build-args: |
            DEBIAN_VERSION=${{ needs.load-env-vars.outputs.DEBIAN_VERSION }}
            SIPP_VERSION=${{ needs.load-env-vars.outputs.SIPP_VERSION }}
            BUILD_FLAGS=${{ needs.load-env-vars.outputs.BUILD_FLAGS }}
            SIPP_SCENARIOS_LOCATION=${{ needs.load-env-vars.outputs.SIPP_SCENARIOS_LOCATION }}
